CONNECTOR_SYNC_JOB_TYPE = "connector_sync"
CONNECTOR_SYNC_QUEUE = "connectors"
DEFAULT_SYNC_LOOKAHEAD_DAYS = 14
DEFAULT_SYNC_LOOKBACK_DAYS = 7
FATIGUE_QUEUE_NAME = "fatigue"
FATIGUE_PATTERN_RECOMPUTE_JOB = "fatigue_patterns.recompute"
